CREATE LOGIN [admin_dso]
    WITH PASSWORD = N'rzVk0NiqdiczQ|yth tstkw6msFT7_&#$!~<r;qzEmwfkskA', SID = 0x07AF78CB64DC30468D529EAC9FD1D7DB, DEFAULT_DATABASE = [DSO_DB], DEFAULT_LANGUAGE = [Français], CHECK_EXPIRATION = ON;

